export interface ProvinceItem {
  id: string;
  name: string;
  keywords: string[];
}

export const VIETNAM_PROVINCES: ProvinceItem[] = [
  { id: '01', name: 'TP. Hồ Chí Minh', keywords: ['hcm', 'ho chi minh', 'sai gon', 'saigon', 'hcmc'] },
  { id: '02', name: 'Hà Nội', keywords: ['ha noi', 'hanoi', 'hn'] },
  { id: '48', name: 'Đà Nẵng', keywords: ['da nang', 'danang', 'dn'] },
  { id: '56', name: 'Nha Trang', keywords: ['nha trang', 'nhatrang', 'nt', 'khanh hoa'] },
  { id: '68', name: 'Đà Lạt', keywords: ['da lat', 'dalat', 'dl', 'lam dong'] },
  { id: '91', name: 'Vũng Tàu', keywords: ['vung tau', 'vungtau', 'vt', 'ba ria'] },
  { id: '92', name: 'Cần Thơ', keywords: ['can tho', 'cantho', 'ct'] },
  { id: '31', name: 'Hải Phòng', keywords: ['hai phong', 'haiphong', 'hp'] },
  { id: '22', name: 'Quảng Ninh', keywords: ['quang ninh', 'ha long', 'halong'] },
  { id: '91_kg', name: 'Kiên Giang', keywords: ['phu quoc', 'phuquoc', 'kien giang'] },
  { id: '46', name: 'Thừa Thiên Huế', keywords: ['hue', 'thua thien hue'] },
  { id: '49', name: 'Quảng Nam', keywords: ['hoi an', 'hoian', 'quang nam'] },
  { id: '37', name: 'Ninh Bình', keywords: ['ninh binh', 'trang an'] },
  { id: '10', name: 'Lào Cai', keywords: ['sapa', 'lao cai'] },
  { id: '52', name: 'Bình Thuận', keywords: ['phan thiet', 'mui ne', 'binh thuan'] },
  { id: '54', name: 'Phú Yên', keywords: ['phu yen', 'tuy hoa'] },
  { id: '51_bd', name: 'Bình Định', keywords: ['quy nhon', 'binh dinh'] },
  { id: '66', name: 'Đắk Lắk', keywords: ['buon ma thuot', 'dak lak'] },
  { id: '74', name: 'Bình Dương', keywords: ['binh duong', 'thu dau mot'] },
  { id: '75', name: 'Đồng Nai', keywords: ['bien hoa', 'dong nai'] },
  { id: '80', name: 'Long An', keywords: ['long an', 'tan an'] },
  { id: '82', name: 'Tiền Giang', keywords: ['my tho', 'tien giang'] },
  { id: '83', name: 'Bến Tre', keywords: ['ben tre'] },
  { id: '84', name: 'Trà Vinh', keywords: ['tra vinh'] },
  { id: '86', name: 'Vĩnh Long', keywords: ['vinh long'] },
  { id: '87', name: 'Đồng Tháp', keywords: ['cao lanh', 'dong thap'] },
  { id: '89', name: 'An Giang', keywords: ['long xuyen', 'chau doc', 'an giang'] },
  { id: '93', name: 'Hậu Giang', keywords: ['hau giang', 'vi thanh'] },
  { id: '94', name: 'Sóc Trăng', keywords: ['soc trang'] },
  { id: '95', name: 'Bạc Liêu', keywords: ['bac lieu'] },
  { id: '96', name: 'Cà Mau', keywords: ['ca mau'] },
  { id: '04', name: 'Cao Bằng', keywords: ['cao bang'] },
  { id: '06', name: 'Bắc Kạn', keywords: ['bac kan'] },
  { id: '08', name: 'Tuyên Quang', keywords: ['tuyen quang'] },
  { id: '11', name: 'Điện Biên', keywords: ['dien bien'] },
  { id: '12', name: 'Lai Châu', keywords: ['lai chau'] },
  { id: '14', name: 'Sơn La', keywords: ['son la', 'moc chau'] },
  { id: '15', name: 'Yên Bái', keywords: ['yen bai', 'mu cang chai'] },
  { id: '17', name: 'Hòa Bình', keywords: ['hoa binh'] },
  { id: '19', name: 'Thái Nguyên', keywords: ['thai nguyen'] },
  { id: '20', name: 'Lạng Sơn', keywords: ['lang son'] },
  { id: '24', name: 'Bắc Giang', keywords: ['bac giang'] },
  { id: '25', name: 'Phú Thọ', keywords: ['phu tho', 'viet tri'] },
  { id: '26', name: 'Vĩnh Phúc', keywords: ['vinh phuc', 'tam dao'] },
  { id: '27', name: 'Bắc Ninh', keywords: ['bac ninh'] },
  { id: '30', name: 'Hải Dương', keywords: ['hai duong'] },
  { id: '33', name: 'Hưng Yên', keywords: ['hung yen'] },
  { id: '34', name: 'Thái Bình', keywords: ['thai binh'] },
  { id: '35', name: 'Hà Nam', keywords: ['ha nam', 'phu ly'] },
  { id: '36', name: 'Nam Định', keywords: ['nam dinh'] },
  { id: '38', name: 'Thanh Hóa', keywords: ['thanh hoa', 'sam son'] },
  { id: '40', name: 'Nghệ An', keywords: ['nghe an', 'vinh', 'cua lo'] },
  { id: '42', name: 'Hà Tĩnh', keywords: ['ha tinh'] },
  { id: '44', name: 'Quảng Bình', keywords: ['quang binh', 'dong hoi', 'phong nha'] },
  { id: '45', name: 'Quảng Trị', keywords: ['quang tri', 'dong ha'] },
  { id: '51_qn', name: 'Quảng Ngãi', keywords: ['quang ngai', 'ly son'] },
  { id: '58', name: 'Ninh Thuận', keywords: ['ninh thuan', 'phan rang'] },
  { id: '62', name: 'Kon Tum', keywords: ['kon tum'] },
  { id: '64', name: 'Gia Lai', keywords: ['gia lai', 'pleiku'] },
  { id: '67', name: 'Đắk Nông', keywords: ['dak nong', 'gia nghia'] },
  { id: '70', name: 'Bình Phước', keywords: ['binh phuoc', 'dong xoai'] },
  { id: '72', name: 'Tây Ninh', keywords: ['tay ninh'] },
  { id: '03', name: 'Hà Giang', keywords: ['ha giang', 'dong van'] }
];
